server:
  port: 9001
spring:
  application:
    name: qcadmin_manager
  datasource:
    url: jdbc:mysql://localhost/qcadmin_manager?characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
     database: MySQL
     show-sql: true
     generate-ddl: true